# Generated by Django 6.1.2 on 2026-10-08 19:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndiceRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('score_economico', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score_cambiario', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score_estabilidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('indice_compuesto', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('nivel_riesgo', models.CharField(choices=[('BAJO', 'Bajo'), ('MODERADO', 'Moderado'), ('ALTO', 'Alto'), ('CRITICO', 'Critico')], max_length=10)),
                ('detalle_calculo', models.JSONField(default=dict)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indices_riesgo', to='paises.pais')),
            ],
            options={
                'ordering': ['-fecha_calculo'],
                'indexes': [models.Index(fields=['pais', 'fecha_calculo'], name='riesgo_indi_pais_id_dfb8e8_idx')],
            },
        ),
    ]
