# Generated by Django 6.1.2 on 2026-10-08 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('ELIMINAR', 'Eliminar'), ('CONSULTAR', 'Consultar'), ('LOGIN', 'Login'), ('EXPORT', 'Exportar')], max_length=10)),
                ('entidad_afectada', models.CharField(max_length=100)),
                ('entidad_id', models.CharField(blank=True, max_length=50)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_actividad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['usuario', 'fecha'], name='core_logact_usuario_47fcf2_idx'), models.Index(fields=['entidad_afectada', 'entidad_id'], name='core_logact_entidad_8dfadd_idx')],
            },
        ),
    ]
