# Generated by Django 6.1.2 on 2026-10-08 20:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('descripcion', models.CharField(blank=True, max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('es_publico', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portafolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_modificacion'],
            },
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_activo', models.CharField(choices=[('RENTA_FIJA', 'Renta fija'), ('RENTA_VARIABLE', 'Renta variable'), ('COMMODITIES', 'Commodities'), ('MONEDA', 'Moneda')], max_length=20)),
                ('monto_inversion_usd', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(10000000)])),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones', to='paises.pais')),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones', to='portafolios.portafolio')),
            ],
            options={
                'ordering': ['-fecha_entrada'],
            },
        ),
        migrations.AddIndex(
            model_name='portafolio',
            index=models.Index(fields=['usuario', 'activo'], name='portafolios_usuario_5a3a2f_idx'),
        ),
        migrations.AddConstraint(
            model_name='portafolio',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('usuario', 'nombre'), name='unico_nombre_portafolio_activo'),
        ),
        migrations.AddIndex(
            model_name='posicion',
            index=models.Index(fields=['portafolio', 'fecha_salida'], name='portafolios_portafo_d226ca_idx'),
        ),
    ]
