# Generated by Django 6.1.2 on 2026-10-08 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('codigo_iso', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('moneda_codigo', models.CharField(max_length=3, unique=True)),
                ('moneda_nombre', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('ANDINA', 'Andina'), ('CONO_SUR', 'Cono Sur'), ('CENTROAMERICA', 'Centroamerica'), ('CARIBE', 'Caribe')], max_length=20)),
                ('latitud', models.DecimalField(decimal_places=4, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=4, max_digits=9)),
                ('poblacion', models.PositiveBigIntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['region'], name='paises_pais_region_6292ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='IndicadorEconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PIB', 'PIB'), ('INFLACION', 'Inflacion'), ('DESEMPLEO', 'Desempleo'), ('BALANZA_COMERCIAL', 'Balanza comercial'), ('DEUDA_PIB', 'Deuda/PIB'), ('PIB_PERCAPITA', 'PIB per capita')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unidad', models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('USD', 'USD'), ('USD_MILES_MILLONES', 'USD miles de millones')], max_length=20)),
                ('anio', models.PositiveIntegerField()),
                ('fuente', models.CharField(choices=[('WORLD_BANK', 'World Bank'), ('MANUAL', 'Manual')], max_length=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='paises.pais')),
            ],
            options={
                'ordering': ['-anio'],
                'indexes': [models.Index(fields=['pais', 'tipo', 'anio'], name='paises_indi_pais_id_e290e3_idx')],
                'constraints': [models.UniqueConstraint(fields=('pais', 'tipo', 'anio'), name='unico_indicador_pais_tipo_anio')],
            },
        ),
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda_destino', models.CharField(default='USD', max_length=3)),
                ('tasa', models.DecimalField(decimal_places=6, max_digits=14)),
                ('fecha', models.DateField()),
                ('variacion_porcentual', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('fuente', models.CharField(choices=[('EXCHANGERATE_API', 'ExchangeRate API'), ('MANUAL', 'Manual')], max_length=20)),
                ('moneda_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_cambio', to='paises.pais', to_field='moneda_codigo')),
            ],
            options={
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['moneda_origen', 'fecha'], name='paises_tipo_moneda__6fa009_idx')],
                'constraints': [models.UniqueConstraint(fields=('moneda_origen', 'fecha'), name='unico_tipocambio_origen_fecha')],
            },
        ),
    ]
