# Generated by Django 6.1.2 on 2026-10-08 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('RIESGO', 'Riesgo'), ('TIPO_CAMBIO', 'Tipo de cambio'), ('INDICADOR', 'Indicador')], max_length=15)),
                ('severidad', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=10)),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='paises.pais')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'leida'], name='alertas_ale_usuario_436e5d_idx'), models.Index(fields=['pais', 'fecha_creacion'], name='alertas_ale_pais_id_605228_idx')],
            },
        ),
    ]
